update_settings(max_parallel_updates=1)

watch_file('/repo/k8s/extension/')
watch_file('/repo/k8s/extension_job/')

if config.tilt_subcommand == 'down':
  local('kubectl delete cm -l lxc.liferay.com/metadataType=dxp')
  local('kubectl delete cm -l lxc.liferay.com/metadataType=ext-init')

include("/workspace/Tiltfile")